services:
  observit:
    image: "observit:latest"
    restart: unless-stopped
    volumes:
      - /opt/observit/collector/logs:/collector/logs
      - /opt/observit/collector/config:/collector/config
      - /opt/observit/collector/keys:/collector/keys
      - /opt/observit/collector/tests:/collector/tests
#    environment:
#      - ENV HTTP_PROXY="http\://20.220.3.113\:8080"
#      - ENV HTTPS_PROXY="https\://20.220.3.113\:8080"
#      - ENV FTP_PROXY="ftp\://20.220.3.113\:8080"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: "grafana/grafana-enterprise:latest"
    restart: unless-stopped
    ports:
    - "443:3000/tcp"
    volumes:
      - /opt/observit/grafana/etc/:/etc/grafana/
      - /opt/observit/grafana/data/grafana:/var/lib/grafana/
    user: "1000"
#    environment:
#      - ENV HTTP_PROXY="http\://20.220.3.113\:8080"
#      - ENV HTTPS_PROXY="https\://20.220.3.113\:8080"
#      - ENV FTP_PROXY="ftp\://20.220.3.113\:8080"
    logging:
       options:
         max-size: "10m"
         max-file: 3

  influxdb:
    image: "influxdb:latest"
    restart: unless-stopped
    ports:
    - "8086:8086/tcp"
    volumes:
      - /opt/observit/influxdb/influxdb:/var/lib/influxdb
      - /opt/observit/influxdb/influxdb2:/var/lib/influxdb2
      - /opt/observit/influxdb/influxdb2-config:/etc/influxdb
      - /opt/observit/influxdb/influxdb2-ssl:/etc/ssl
    user: "1000"
    environment:
#      - ENV HTTP_PROXY="http\://20.220.3.113\:8080"
#      - ENV HTTPS_PROXY="https\://20.220.3.113\:8080"
#      - ENV FTP_PROXY="ftp\://20.220.3.113\:8080"
      - INFLUXD_TLS_CERT=/etc/ssl/influxdb.crt
      - INFLUXD_TLS_KEY=/etc/ssl/influxdb.key
    logging:
       options:
         max-size: "10m"
         max-file: 3
